version: "3"
volumes:
  pgdata:
services:
  python:
    # image: python:3.7
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./budgetproject:/app
    ports:
      - 8000:8000
    # command: bash -c "cd /app && pip install -r requirements.txt && python manage.py runserver 0:8000"
    # command: sleep infinity
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
#    image: postgres:9.6
    image: postgres:10.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432

